import { parseAbi } from "viem";

export const poolAbi = parseAbi([
  "function active() view returns (bool)",
  "function pauseMask() view returns (uint8)",
  "function currentEpochId() view returns (uint64)",
  "function lastTerminalEpochId() view returns (uint64)",
  "function nextWithdrawalId() view returns (uint64)",
  "function nextFifoSequence() view returns (uint64)",
  "function activeSettlementId() view returns (uint64)",
  "function PARTICIPANT_CAPACITY() view returns (uint256)",
  "function epochDuration() view returns (uint64)",
  "function requestTimeout() view returns (uint64)",
  "function fulfillmentTimeout() view returns (uint64)",
  "function drawTimeout() view returns (uint64)",
  "function winnerAclDelayBlocks() view returns (uint64)",
  "function slotBondWei() view returns (uint96)",
  "function liquidityTargetBps() view returns (uint16)",
  "function DEPOSIT_ROUTE() view returns (bytes4)",
  "function slotOf(address owner) view returns (bool occupied, uint8 slot)",
  "function slotPublic(uint8 slot) view returns (address owner, uint8 status, uint96 bondWei, uint64 activeWithdrawalId, uint64 lastReferencedEpoch)",
  "function principalHandle(address owner) view returns (bytes32)",
  "function weightHandles(address owner) view returns (bytes32 eligible, bytes32 pending)",
  "function epochPublic(uint64 epochId) view returns (uint8 status, uint64 openedAt, uint64 closesAt, uint64 frozenAt, uint64 requestDeadline, uint8 frozenSlotCount, bytes32 snapshotCommitment)",
  "function epochSlotOwner(uint64 epochId, uint8 slot) view returns (address)",
  "function epochWeightHandle(uint64 epochId, uint8 slot) view returns (bytes32)",
  "function epochRandomness(uint64 epochId) view returns (uint256 requestId, uint64 fulfillmentDeadline, uint256 randomWord, uint64 fulfilledAt, uint64 drawDeadline)",
  "function epochWinner(uint64 epochId) view returns (bytes32 encryptedWinner, uint64 aclGrantNotBeforeBlock, address finalizedWinner, bool winnerFinalized)",
  "function prizeHandle(uint64 epochId) view returns (bytes32)",
  "function withdrawalHandle(uint64 withdrawalId) view returns (bytes32)",
  "function withdrawalPublic(uint64 withdrawalId) view returns (uint8 slot, address owner, uint64 createdAt, uint64 fifoSequence, uint64 settlementId, uint32 version, uint8 status, bytes32 routingHandle, bytes32 completionHandle)",
  "function fifoHead() view returns (uint64 withdrawalId, uint8 status)",
  "function reserveSlot() payable returns (uint8 slot)",
  "function releaseSlot(uint8 slot)",
  "function requestWithdrawal(bytes32 requestedInput, bytes inputProof, bool closing) returns (uint64 withdrawalId)",
  "function freezeEpoch(uint64 epochId)",
  "function abandonUnrequestedEpoch(uint64 epochId)",
  "function requestEpochRandomness(uint64 epochId) returns (uint256 requestId)",
  "function syncEpochRandomness(uint64 epochId)",
  "function abandonUnfulfilledEpoch(uint64 epochId)",
  "function abandonUnexecutedEpoch(uint64 epochId)",
  "function executeEncryptedDraw(uint64 epochId)",
  "function finalizeWinner(uint64 epochId, address clearWinner, bytes proof)",
  "function claimPrize(uint64 epochId)",
  "function openNextEpoch()",
  "function finalizeWithdrawalRouting(uint64 requestId, bool hasRemainder, bytes proof)",
  "function serviceFifoHead() returns (uint64 withdrawalId)",
  "function finalizeWithdrawalCompletion(uint64 requestId, bool isZero, bytes proof)",
  "function beginInvestmentSettlement(uint64 publicCap)",
  "function beginWithdrawalSettlement(uint64 publicCap)",
  "function beginYieldHarvest(uint64 publicCap)",
  "event EpochOpened(uint64 indexed epochId, uint64 openedAt, uint64 closesAt)",
  "event EpochFrozen(uint64 indexed epochId, bytes32 snapshotCommitment, uint8 frozenSlotCount, uint64 requestDeadline)",
  "event EpochRandomnessRequested(uint64 indexed epochId, uint256 requestId, uint64 fulfillmentDeadline)",
  "event EpochRandomnessSynchronized(uint64 indexed epochId, uint256 requestId, uint256 randomWord, uint64 drawDeadline)",
  "event EncryptedDrawExecuted(uint64 indexed epochId, bytes32 winnerHandle, uint64 aclGrantNotBeforeBlock)",
  "event WinnerFinalized(uint64 indexed epochId, address indexed winner)",
  "event EpochNoWinner(uint64 indexed epochId)",
  "event EpochAbandoned(uint64 indexed epochId, uint8 reason)",
  "event EpochTerminal(uint64 indexed epochId, uint8 outcome)",
  "event SlotReserved(address indexed owner, uint8 indexed slot)",
  "event SlotClosing(address indexed owner, uint8 indexed slot, uint64 indexed withdrawalId)",
  "event SlotReleased(address indexed owner, uint8 indexed slot, uint96 bondWei)",
  "event DepositProcessed(address indexed owner, uint8 indexed slot, uint64 indexed pendingEpoch)",
  "event WithdrawalRequested(uint64 indexed requestId, uint8 indexed slot, address indexed owner)",
  "event WithdrawalRoutingProofReady(uint64 indexed requestId, bytes32 booleanHandle, uint32 version)",
  "event WithdrawalRouted(uint64 indexed requestId, uint8 route, uint64 fifoSequence)",
  "event WithdrawalPayoutProcessed(uint64 indexed requestId, uint32 version)",
  "event WithdrawalCompletionProofReady(uint64 indexed requestId, bytes32 booleanHandle, uint32 version)",
  "event WithdrawalCompleted(uint64 indexed requestId, address indexed owner)",
  "event PrizeClaimProcessed(uint64 indexed epochId, address indexed winner)",
]);

export const tokenAbi = parseAbi([
  "function decimals() view returns (uint8)",
  "function symbol() view returns (string)",
  "function underlying() view returns (address)",
  "function rate() view returns (uint256)",
  "function confidentialBalanceOf(address account) view returns (bytes32)",
  "function wrap(address to, uint256 amount) returns (bytes32)",
  // ERC-7984 returns the encrypted amount actually transferred (euint64),
  // represented as bytes32 in the ABI. It is not a Solidity bool.
  "function confidentialTransferAndCall(address to, bytes32 amount, bytes inputProof, bytes data) returns (bytes32)",
  "function unwrap(address from, address to, bytes32 amount) returns (bytes32)",
  "function unwrap(address from, address to, bytes32 amount, bytes inputProof) returns (bytes32)",
  "function unwrapAmount(bytes32 requestId) view returns (bytes32)",
]);

export const underlyingTokenAbi = parseAbi([
  "function balanceOf(address account) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 amount) returns (bool)",
]);

export const vrfAbi = parseAbi([
  "function requestForEpoch(uint64 epochId) view returns (uint256)",
  "function getFulfillment(uint256 requestId) view returns (uint64 epochId, bytes32 snapshotCommitment, uint256 randomWord, uint64 fulfilledAt, uint64 fulfilledBlock, bool fulfilled)",
  "function pendingRequestCount() view returns (uint256)",
  "event VrfRequestCreated(uint256 indexed requestId, uint64 indexed epochId, bytes32 snapshotCommitment, uint256 price)",
  "event VrfFulfilled(uint256 indexed requestId, uint64 indexed epochId, uint64 fulfilledAt)",
]);

export const settlementAbi = parseAbi([
  "function activeSettlementId() view returns (uint64)",
  "function strategy() view returns (address)",
  "function strategyShares() view returns (uint256)",
  "function deployedPrincipal() view returns (uint256)",
  "function investmentsPaused() view returns (bool)",
  "function lossMode() view returns (bool)",
  "function settlementPublic(uint64 settlementId) view returns (uint8 kind, uint8 status, uint8 retryStage, uint64 createdAt, uint64 publicCap, bytes32 aggregateHandle, uint64 clearAggregate, bytes32 wrapperRequestId, uint256 publicAssetsRequested, uint256 publicAssetsReceived, bytes32 returnedHandle, bytes32 failureCode, uint32 attempt)",
  "function executeSettlement(uint64 settlementId)",
  "function retrySettlement(uint64 settlementId)",
  "function finalizeInvestmentAggregate(uint64 settlementId, uint64 clearAmount, bytes proof)",
  "function finalizePrincipalRedemption(uint64 settlementId, uint64 clearAmount, bytes proof)",
  "event SettlementStarted(uint64 indexed settlementId, uint8 kind, uint64 publicCap, bytes32 aggregateHandle)",
  "event SettlementAggregateFinalized(uint64 indexed settlementId, uint64 clearAggregate)",
  "event SettlementFailed(uint64 indexed settlementId, uint8 stage, bytes32 failureCode, uint32 attempt)",
  "event SettlementRetried(uint64 indexed settlementId, uint32 attempt)",
  "event SettlementCompleted(uint64 indexed settlementId)",
]);
